### ISSUE TITLE
Installation-connected typo in README

### ISSUE THREAD

**Issue by nerett** [sin-diesel/gnu-koryavov#10]
# Description
`README` has a non-critical typo in the **Installation** section, that prevents `cd` from runnung. So, **section 1** should be replaced with **section 2**.

### section 1:
```shell
git clone https://github.com/sin-diesel/gnu-koryavov
cd gnu-koyravov
./install.sh
```

### section 2:
```shell
git clone https://github.com/sin-diesel/gnu-koryavov
cd gnu-koryavov
./install.sh
```

**Comment by sin-diesel** [comment]
I don't see diff, might be cyrillic `c` instead of latin one.

**Comment by Hollbrok** [comment]
> I don't see diff, might be cyrillic `c` instead of latin one.

Should be gnu-koRYavov instead of gnu-koYRavov
[YR --> RY].
