### ISSUE TITLE
Bug: incorrect output for invalid problem number

### ISSUE THREAD

**Issue by nerett** [sin-diesel/gnu-koryavov#2]
Script displays success message without problem number when trying to create a request for a non-existent problem or proceeding with bare input

### Script behavior

```
Введите номер семестра: 2
Введите номер задачи: 3
Задача 3 найдена на странице №!
```

### Original website behavior

```
№ задачи: 3
Укажите номер задачи корректно!
```
## Screenshots

![Screenshot_20220329_173550](https://user-images.githubusercontent.com/89396128/160636525-542ab230-c587-4e06-9a54-4ae8b9e34a58.png)
![Screenshot_20220329_173437](https://user-images.githubusercontent.com/89396128/160636517-14ba12c3-9e39-422e-980a-93c6c0cf2dfe.png)

**Comment by Hollbrok** [comment]
There is also the problem when the task number is specified correctly and the website says that the task was not found, but the script returns **Задача 5.55 найдена на странице №!**
