### ISSUE TITLE
installation error

### ISSUE THREAD

**Issue by Hollbrok** [sin-diesel/gnu-koryavov#8]
If you follow the instructions: 
![image](https://user-images.githubusercontent.com/70323332/161255757-315d7d04-cceb-4b80-a701-80514ee382bb.png)
it gives an error:
cp: невозможно создать обычный файл '/home/hollbrok/gnu-koryavov/': Это не каталог

**Comment by nerett** [comment]
Installation instructions work properly on Kubuntu 20.04.4. Also tested on Debian 11:
![Screenshot_20220401_211425](https://user-images.githubusercontent.com/89396128/161319628-eb3db01b-03de-4859-b135-bc46c8858439.png)
Please specify your system

**Comment by nerett** [comment]
#### Update:
Running instructions from the home directory also works properly (Debian 11):
![Screenshot_20220401_212144](https://user-images.githubusercontent.com/89396128/161320727-29db4d8e-fa00-4358-a4b7-c8ef3c984cf9.png)

**Comment by sin-diesel** [comment]
All installation script should come with `sudo`, at first glance this is the main problem I see.

**Comment by sin-diesel** [comment]
Try creating gnu-koyravov directory before using `cp` on it.

**Comment by Hollbrok** [comment]
It seems like i forgot to run **install.sh** before running **cp okular.sh ~/gnu-koryavov**
