### ISSUE TITLE
task status output error

### ISSUE THREAD

**Issue by Hollbrok** [sin-diesel/gnu-koryavov#9]
The website output is as follows:
![image](https://user-images.githubusercontent.com/70323332/161268109-f20e4bbc-9dd4-4222-9f60-0af157dd73c2.png)

but i got this:
![image](https://user-images.githubusercontent.com/70323332/161268163-c282550e-cbc9-470c-a064-9e842abedd0d.png)

instead of  "Задача $zad не найдена в корявнике:("

**Comment by nerett** [comment]
This issue duplicates already existing #2 issue
